# Generated by Django 4.0.2 on 2022-03-31 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('s_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('m_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('capacity', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('b_id', models.AutoField(default=1001, primary_key=True, serialize=False)),
                ('b_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.shows')),
            ],
        ),
    ]
