# Generated by Django 4.0.2 on 2022-03-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_movie_alter_shows_m_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='b_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shows',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
